### PR TITLE
pytest-httpx v0.35.0

### PR DESCRIPTION
**Pull request by johanols**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by johanols** [comment]
Based on https://github.com/conda-forge/pytest-httpx-feedstock/pull/39 but with fixed build step.

**Comment by johanols** [comment]
License is being package

```
?rw-rw-r-- 0/0       1071 2024-12-10 13:24:44 site-packages/pytest_httpx-0.35.0.dist-info/LICENSE
```

**Comment by johanols** [comment]
@dgasmith / @owenlamont Sorry for bugging you, but do you think we can get this merged soon?

**Comment by owenlamont** [comment]
I'll look at this now - sorry have been away a few weeks.

**Review by owenlamont — APPROVED** [review]
Looks good to me

**Pull request merged**
